---
# yamllint disable rule:line-length
workflows:
  version: 2.1
  build:
    jobs:
      - build-plugin:
          context:
            - unreal-engine-ci
          matrix:
            parameters:
              unreal-engine-version: [
                "4.27.0", "5.0.0", "5.1.0", "5.2.0", "5.3.0"
              ]
              version: ["free", "full"]

version: 2.1
jobs:
  build-plugin:
    parameters:
      unreal-engine-version:
        type: string
      version:
        type: string
    docker:
      - image: ghcr.io/epicgames/unreal-engine:dev-slim-<< parameters.unreal-engine-version >>
        auth:
          username: $GHCR_USERNAME
          password: $GHCR_PASSWORD
    steps:
      - checkout
      - run:
          name: Run scripts for the license removing
          command: bash tools/remove_license.sh Kdtree << parameters.version >>
      - run:
          name: Run scripts for the code removing
          command: bash tools/remove_code.sh Kdtree << parameters.unreal-engine-version >> << parameters.version >> .
      - run:
          name: "Run scripts for the release"
          command: bash tools/replace_engine_version.sh Kdtree << parameters.unreal-engine-version >>
      - run:
          name: "Build Plugin"
          command: |
            /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh BuildPlugin \
              -Plugin=${PWD}/Kdtree/Kdtree.uplugin \
              -Package=/tmp \
              -Rocket
